services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    image: ats-api-2
    ports:
      - "5000:5000"
    networks:
      - ats-network
  client:
    build:
      context: .
      dockerfile: dockerfile.client
    image: ats-client-2
    ports:
      - "3000:3000"
    networks:
      - ats-network

networks:
  ats-network:
    driver: bridge